version: '2'
volumes:
  db:
  phpmyadmin:
services:
  mariadb:
   image: mariadb
   environment:
    MYSQL_ROOT_PASSWORD: kj187xklj3d3211
   volumes:
    - db:/var/lib/mysql
  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   links:
    - mariadb:db
   depends_on:
    - mariadb
   environment:
    - PMA_ARBITRARY=1
   restart: always
   ports:
    - 8080:80
   volumes:
    - phpmyadmin:/sessions
  web:
    build: ./projectConfig/
    depends_on:
      - mariadb
    links:
      - mariadb:db
    ports:
      - 80:80
    volumes:
      - ./wwwFiles:/var/www/html
